### ISSUE TITLE
Wrapped input spills over container with long message in it

### ISSUE THREAD

**Issue by yevhen-logosha** [chatscope/chat-ui-kit-styles#4] opened 2021-04-16 17:31 UTC
@supersnager got one more mate. :) 
if you go to https://chatscope.io/storybook/react/?path=/docs/components-chatcontainer--wrapped-message-input
and type in really looooooong message, input pushes buttons beyond container. Looks like setting `width: 50%` on input if its wrapped resolves issue.

**Comment by supersnager** [comment] 2021-04-22 13:14
@yevhen-logosha Thank you for reporting this.
It was not a bug in the components css, but in the styling of the story. The Storybook on the website is now fixed.

**Closed as completed by supersnager** 2021-04-22 13:14 UTC
Labels: bug

**Comment by yevhen-logosha** [comment] 2021-04-22 13:33
@supersnager just fyi, was able to reproduce it, link to storybook was just as a reference ;)
